env:
  es2022: true
  node: true
  browser: true
  worker: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'google'
  - 'prettier'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 'latest'
  sourceType: 'module'
plugins:
  - 'react'
settings:
  react:
    version: 'detect'
rules:
  no-var: 'off'
  require-jsdoc: 'off'
