'*.([cm]js|js?x)': 'eslint --config ./config/.eslintrc.yaml --ignore-path .gitignore --fix --ext .cjs,.js,.jsx,.mjs,.ts'
'*.css': 'stylelint --config ./config/.stylelintrc.yaml --ignore-path .gitignore --fix'
'*': 'prettier --config ./config/.prettierrc.yaml --ignore-path .gitignore --ignore-unknown --write'
