'*.([cm]js|js?x)': 'eslint --config ./config/.eslintrc.yaml --ignore-path .gitignore --fix --ext .js,.jsx,.ts,.mjs,.cjs'
'*.css': 'stylelint --config ./config/.stylelintrc.yaml --ignore-path .gitignore --fix'
'*': 'prettier --config ./config/.prettierrc.yaml --ignore-path .gitignore --ignore-unknown --write'
